### ISSUE TITLE
Positional tracking

### ISSUE THREAD

**Issue by Russ76** [stereolabs/zed-ros-examples#1]
With this information, would it be hard to write a "teach and repeat" module? One drives the robot over a course and in the repeat phase, the robot follows the info or bag file to repeat the same course. This would be great for a security observation route.

**Comment by Myzhar** [comment]
Hi @Russ76 
it can be a possible application.
Please share your work with us if you plan to make it

**Comment by Myzhar** [comment]
@Russ76 I close the issue. Please feel free to re-open it if you have news
