### ISSUE TITLE
Difference between zed_nodelet_laserscan.launch and zed_laserscan_nodelet.launch

### ISSUE THREAD

**Issue by saeedarabi92** [stereolabs/zed-ros-examples#11]
I ran both zed_laserscan_nodelet.launch and zed_nodelet_laserscan.launch and was able to see the 2D lasescan. What is the difference between these two launch files as they seems to be at least functionally the same.

Thank you.

**Comment by Myzhar** [comment]
Hi @saeedarabi92 
It's a simple renaming. The old `zed_laserscan_nodelet.launch` file should not be there. I'm going to remove it.

Thank you for reporting
