### ISSUE TITLE
ZED2 is not capable to track AR tags with zed_ar_track_alvar

### ISSUE THREAD

**Issue by LucaRoma97** [stereolabs/zed-ros-examples#13]
Hi everyone!
I'm working on my thesis about an autonomous charging system. 
I bought a ZED2 camera and a Jetson Nano. After having installed the SDK of the ZED and ROS (Melodic version), I cloned both the zed-ros-examples ([](https://github.com/stereolabs/zed-ros-examples)) and zed-ros-wrapper  ([]((https://github.com/stereolabs/zed-ros-wrapper)).) I also change the zed_wrapper .launch file inside the zed_ar_track_alvar.launch (zed2.launch in place of zed_camera.launch). But when I try to launch the zed_ar_track_alvar.launch, the _Rviz visualizations_ show me warnings and errors and I can't see the output of the camera.
![first_rvizz](https://user-images.githubusercontent.com/63620182/81364385-5abe3680-909a-11ea-85d1-4b8c7c93e861.png)
If I try to visualize the _rqt_graph_:
![rqt_graph1](https://user-images.githubusercontent.com/63620182/81364503-9e18a500-909a-11ea-890a-6d6b3007a1f3.png)
Then, I tried to change the _Image Topic_ of Left Image, Left Camera and Tags  ,as shown below:
![second_rvizz](https://user-images.githubusercontent.com/63620182/81364891-96a5cb80-909b-11ea-9165-747eaf5789eb.png)
Now I can visualize the output of the camera, but it is not yet capable to track the ar codes and the rqt_graph now is the following:
![rqt_graph2](https://user-images.githubusercontent.com/63620182/81364931-b0dfa980-909b-11ea-82ce-451443afe59f.png)
It seems that the node zed_ar_track_alvar doesn't communicate with the camera ones.
I tried to change several names to the topics without any results. Someone has some advices for tracking the ar tags?
Thank you in advance.

**Comment by LucaRoma97** [comment]
I've just fixed the Camera model error, but it still doesn't work.

**Comment by ArghyaChatterjee** [comment]
@LucaRoma97 how have you fixed the camera model error?

**Comment by Myzhar** [comment]
Fixed with https://github.com/stereolabs/zed-ros-examples/commit/0e924d870e73ef778e73afa948e3c56f87cb84ab
