### ISSUE TITLE
[Question] Zed_rtabmap.launch

### ISSUE THREAD

**Issue by ManChrys** [stereolabs/zed-ros-examples#23]
Hello guys,

im running the launch file and worked fine but while im exporting the pointcloud or when im doing <<edit-->view point cloud>>  then crashes. Im trying it with regenerate cloud filter and cloud filtering with the defaults params.

ERROR NUMBER 1

![Screenshot from 2021-01-10 20-35-15](https://user-images.githubusercontent.com/67521662/104132030-5f529180-5383-11eb-9ac4-66066e3c059e.png)

ERROR NUMBER 2

![Screenshot from 2021-01-10 20-44-09](https://user-images.githubusercontent.com/67521662/104132251-aa20d900-5384-11eb-9098-f47fa4223eb1.png)

im following the path but the log file doesnt appear to exist.

![Screenshot from 2021-01-10 20-36-45](https://user-images.githubusercontent.com/67521662/104132076-d25c0800-5383-11eb-8704-e52f3be46602.png)

[roslaunch-geo-305.log](https://github.com/stereolabs/zed-ros-examples/files/5793130/roslaunch-geo-305.log)
[roslaunch-geo-1835.log](https://github.com/stereolabs/zed-ros-examples/files/5793131/roslaunch-geo-1835.log)
[roslaunch-geo-30865.log](https://github.com/stereolabs/zed-ros-examples/files/5793137/roslaunch-geo-30865.log)

i think these are the logs because i cant find 
log file: /home/geo/.ros/log/88e098ea-5369-11eb-8217-3c6aa7d21fc7/zed-rtabmapviz-3*.log
log file: /home/geo/.ros/log/88e098ea-5369-11eb-8217-3c6aa7d21fc7/zed-zed_node-2*.log

I dont know what im doing wrong.Any suggestion? :P 

Thanks in advance.

**Comment by Myzhar** [comment]
Hi @ManChrys 
This is a problem with RTABmap not related to the ZED wrapper. Try asking on the RTABmap repo:
 https://github.com/introlab/rtabmap_ros

**Comment by ManChrys** [comment]
Ok thank you my friend.
