### ISSUE TITLE
[Question] Finer pointcloud

### ISSUE THREAD

**Issue by ManChrys** [stereolabs/zed-ros-examples#24]
Hello guys,

when im using zed_rtabmap_example i have this result

![Screenshot from 2021-01-11 16-51-29](https://user-images.githubusercontent.com/67521662/104197570-dba1af00-542d-11eb-8209-156869cf8a89.png)

Post processing makes it a little better but still have that "noise". Which parameters improve the pointcloud?

Thanks again guys.

**Comment by Myzhar** [comment]
Hi @ManChrys 
this is another question to post on the RTABmap repository/forum.
Those are the better places to get more precise replies about how RTABmap works

**Comment by ManChrys** [comment]
oh ok. i miss understood it because the project is in this repo. My bad then. Thank you again my friend.
