### ISSUE TITLE
Catkin_make compilation error 

### ISSUE THREAD

**Issue by Alataishi** [stereolabs/zed-ros-examples#26]
I cloned both zed_ros_wrapper and zed_ros_examples, and when I enter catkin_make it shows a lot of error in the files zed_od_display.cpp, zed_od_display.hpp, zed_od_info.cpp and zed_od_info.hpp

![image](https://user-images.githubusercontent.com/70470607/109954800-32738880-7cfb-11eb-84b3-1b1ba769fae5.png)

![image](https://user-images.githubusercontent.com/70470607/109954842-3e5f4a80-7cfb-11eb-9f64-6d34aac4cbf8.png)

**Comment by Myzhar** [comment]
Hi @Alataishi 
I need more information to help you to solve your issue.
What is the version of the ZED SDK that you installed? What is your OS? What versions of ROS Wrapper and ROS Examples have you cloned?

**Comment by Alataishi** [comment]
@Myzhar Hello 
I am actually new to ROS , but anyway I am using Ubuntu 16.04, 
ZED SDK for Ubuntu 16 version 3.4.1
I cloned the the zed wrapper and examples from master branch

**Comment by Alataishi** [comment]
it turns out that i have to enable C++11
