### ISSUE TITLE
RTAP Map example[Question] 

### ISSUE THREAD

**Issue by MahmoudF98** [stereolabs/zed-ros-examples#29]
Where in the RTAP map example, the point cloud or the laser scan being subscribed?

Thanks in advance.

**Comment by Myzhar** [comment]
RTABmap is using neither point cloud, nor laser scan, but depth map:
https://github.com/stereolabs/zed-ros-examples/blob/master/examples/zed_rtabmap_example/launch/zed_rtabmap.launch#L43-L51
