### ISSUE TITLE
[BUG] Can't download 3D Map nor export 3D cloud

### ISSUE THREAD

**Issue by joseandres94** [stereolabs/zed-ros-examples#37]
Using rtabmap with ZED I am not able to download the 3D Map from the RViz window, by clicking in "Download Map" within "MapCloud" display. When I click on it, it appears:

> MapCloudDisplay: Can't call "/zed/rtabmap/get_map_data" service. Tip: if rtabmap node is not in rtabmap namespace, you can remap the service to "get_map_data" in the launch file like: <remap from="rtabmap/get_map_data" to="get_map_data"/>.

Also, in the "RTAB-Map [ROS]" window, I am not able to export the clouds that it is supposed to generate. As you can see in the image, it is gray coloured and unable to use it.

![Screenshot from 2021-07-23 19-55-49](https://user-images.githubusercontent.com/42548922/126822283-e1fa98e7-f4c0-43d3-b7f4-02b46d847b0b.png)

Could you tell me what is happening and how could I fix it? I really need to obtain a point cloud but I cannot get it and I don't know what else could I try.

Thank you.

**Device information:**
 - OS: Ubuntu
 - OS version: 18.04
 - CPU: Jetson AGX Xavier
 - GPU Nvidia:  Tegra
 - ZED SDK Version: v.3.5
 - ROS Wrapper version: ROS Melodic
 - ROS rtabmap version: 0.20.9
 - ROS rtabmap_ros version: 0.20.9

**Comment by Myzhar** [comment]
We are adding this feature:
https://github.com/stereolabs/zed-ros-wrapper/issues/749
