### ISSUE TITLE
[ INFO] [1631333251.179704795]: ZED connection -> CAMERA STREAM FAILED TO START?

### ISSUE THREAD

**Issue by anchao1997** [stereolabs/zed-ros-examples#39]
When I run "roslaunch zed_rtabmap_example zed_rtabmap.launch", the terminal always show [ INFO] [1631333251.179704795]: ZED connection -> CAMERA STREAM FAILED TO START, I have run the "roslaunch zed_wrapper zed2.launch"

here are the specific infomation of terminnal:
[ INFO] [1631333283.747716508]: ZED connection -> CAMERA STREAM FAILED TO START
[ WARN] [1631333284.801954298]: /zed/rtabmap: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
/zed/rtabmap subscribed to (approx sync):
   /zed/zed_node/rgb/image_rect_color \
   /zed/zed_node/depth/depth_registered \
   /zed/zed_node/rgb/camera_info
[ WARN] [1631333285.448819855]: /zed/rtabmapviz: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
/zed/rtabmapviz subscribed to:
   /zed/zed_node/odom

and I have follow the rtabmap tutorials to make some changes

**Comment by Myzhar** [comment]
@anchao1997 you must not start a separated zed node, the example launch file starts everything you need with the correct topics remappings:
https://github.com/stereolabs/zed-ros-examples/blob/master/examples/zed_rtabmap_example/launch/zed_rtabmap.launch
