### ISSUE TITLE
I encountered a bug while using the zed_multi_cam.launch from the zed-ros-example package.

### ISSUE THREAD

**Issue by sdk17586** [stereolabs/zed-ros-examples#52]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I encountered a bug while using the zed_multi_cam.launch from the zed-ros-example package.

good case

[ INFO] [1693355823.558812812]:  *** Opening ZED X...
[ INFO] [1693355823.604383824]:  * Camera coordinate system -> Right HANDED Z UP and X FORWARD
[ INFO] [1693355823.604560624]:  *** Opening ZED X Mini...
[ INFO] [1693355824.034480708]: Stereo is NOT SUPPORTED
[ INFO] [1693355824.034632676]: OpenGL device: NVIDIA Tegra Orin (nvgp
[ INFO] [1693355492.062182718]: OpenGl version: 4.6 (GLSL 4.6).
[ INFO] [1693355497.090045828]: ZED connection -> SUCCESS

bad case

[ INFO] [1693355870.361131585]:  *** Opening ZED X Mini...
[ INFO] [1693355870.412381492]:  * Camera coordinate system -> Right HANDED Z UP and X FORWARD
[ INFO] [1693355870.412560053]:  *** Opening ZED X...
[ INFO] [1693355870.493121089]: ZED connection -> CAMERA NOT DETECTED
[ INFO] [1693355870.543917298]: ZED connection -> CAMERA NOT DETECTED

When opening "zedx" first and then opening "zedxm," it shows "ZED connection -> SUCCESS." However, when opening "zedxm" first and then opening "zedx," it displays "ZED connection -> CAMERA NOT DETECTED."

### Steps to Reproduce

1. roslaunch zed_multicamera_example zed_multi_cam.launch
2.
3.
...

### Expected Result

[ INFO] [1693355823.558812812]:  *** Opening ZED X...
[ INFO] [1693355823.604383824]:  * Camera coordinate system -> Right HANDED Z UP and X FORWARD
[ INFO] [1693355823.604560624]:  *** Opening ZED X Mini...
[ INFO] [1693355824.034480708]: Stereo is NOT SUPPORTED
[ INFO] [1693355824.034632676]: OpenGL device: NVIDIA Tegra Orin (nvgp
[ INFO] [1693355492.062182718]: OpenGl version: 4.6 (GLSL 4.6).
[ INFO] [1693355497.090045828]: ZED connection -> SUCCESS

and

[ INFO] [1693355870.361131585]:  *** Opening ZED X Mini...
[ INFO] [1693355870.412381492]:  * Camera coordinate system -> Right HANDED Z UP and X FORWARD
[ INFO] [1693355870.412560053]:  *** Opening ZED X...
[ INFO] [1693355870.493121089]: ZED connection -> CAMERA NOT DETECTED
[ INFO] [1693355870.543917298]: ZED connection -> CAMERA NOT DETECTED

### Actual Result

help

### ZED Camera model

ZED

### Environment

```shell
jetson agx orin devkit
```

**Comment by Myzhar** [comment]
Duplicated. Solving this on the forum:
https://community.stereolabs.com/t/i-encountered-a-bug-while-using-the-zed-multi-cam-launch-from-the-zed-ros-example-package/3409
Please NEVER cross-post.
