### ISSUE TITLE
No such file or directory  #include <zed_interfaces/ObjectStamped.h>

### ISSUE THREAD

**Issue by saeedarabi92** [stereolabs/zed-ros-examples#9]
Hi,

When I tried to compile the zed-ros-examples with my Jetson TX2, received this error:

`/home/nvidia/Aria/src/zed-ros-examples/tutorials/zed_obj_det_sub_tutorial/src/zed_obj_det_sub_tutorial.cpp:28:10: fatal error: zed_interfaces/ObjectStamped.h: No such file or directory
 #include <zed_interfaces/ObjectStamped.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`

What I am I missing?

Thanks

**Comment by Myzhar** [comment]
Hi @saeedarabi92 
You have surely updated the `zed-ros-wrapper` repository, but not the `zed-ros-examples` repository.
Try this:
`roscd zed_examples`
`git pull`
Then try to recompile

**Comment by saeedarabi92** [comment]
This solved my problem. Thanks. Closing this.

**Comment by kuzhang** [comment]
Hi Myzhar, I face the same issues. I have tried your suggestion, but it didn't work. Also,  I cannot find the .h files inside the zed_interface packages. What did I miss?  Thank you.

> Hi @saeedarabi92
> You have surely updated the `zed-ros-wrapper` repository, but not the `zed-ros-examples` repository.
> Try this:
> `roscd zed_examples`
> `git pull`
> Then try to recompile

**Comment by Myzhar** [comment]
@kuzhang before compiling try to delet the `build` and `devel folders in your catkin workspace to clean the CMake cache

**Comment by kuzhang** [comment]
> @kuzhang before compiling try to delet the `build` and `devel folders in your catkin workspace to clean the CMake cache

Thanks for the prompt reply. I had tried to clean the WS. It didn't work in my case. I found out it is the rosdep problem. Before I had run the 
```shell
rosdep install --from-paths src --ignore-src -r -y
```

I feel like the rosdep will look at the wrong place.

So I reinstall the rosdep with 

```shell
rosdep init
```
and skip the rosdep install , and execute the 
```shell
catkin_make -DCMAKE_BUILD_TYPE=Release
``` 
and the compiling success.
